// routes/index.js
import express from 'express';
import productoRoutes from './producto.routes.js';
import clienteRoutes from './cliente.routes.js';
import pedidoRoutes from './pedido.routes.js';
import publicRoutes from './public.routes.js';
import usuarioRoutes from './usuario.routes.js';
import paginaRoutes from './pagina.routes.js';
import categoriaRoutes from './categoria.routes.js';
import subcategoriaRoutes from './subcategoria.routes.js';
import authRoutes from './auth.routes.js';
import estadisticasRoutes from './estadisticas.routes.js';
import logClienteRoutes from './logCliente.routes.js';
import notificacionRoutes from './notificacion.routes.js';
import reporteProduccionRoutes from "./reporteProduccion.routes.js";
import plantaRoutes from './planta.routes.js';
import rolUsuarioRoutes from './rolUsuario.routes.js';
import estadoPedidoRoutes from './estadoPedido.routes.js';
import graficosRoutes from './graficos.routes.js';
import informeSemanal from './informeSemanal.routes.js';
import duxRoutes from './dux.routes.js'
//import chatRoutes from './chat.route.js';
import conversacionBotRoutes from './conversacionBot.routes.js';
import facturaRoutes from './factura.routes.js';
import eficienciaRoutes from "./eficiencia.routes.js";
import personalDuxRoutes from "./personalDux.routes.js";
import MateriaPrimaRoutes from './materiaPrima.routes.js';
import composicionRoutes from './composicion.routes.js';
import ordenTrabajoRoutes from './ordenTrabajo.routes.js';
import proveedorRoutes from './proveedor.routes.js';
import ConfiguracionSistema from './configuracionSistema.routes.js';

const router = express.Router();

router.use('/productos', productoRoutes);
router.use('/clientes', clienteRoutes);
router.use('/pedidos', pedidoRoutes);
router.use('/public', publicRoutes);
router.use('/usuarios', usuarioRoutes);
router.use('/pagina', paginaRoutes);
router.use('/categorias', categoriaRoutes);
router.use('/subcategorias', subcategoriaRoutes);
router.use('/auth', authRoutes);
router.use('/estadisticas', estadisticasRoutes);
router.use('/logs-cliente', logClienteRoutes);
router.use('/notificaciones', notificacionRoutes);
router.use('/produccion-diaria', reporteProduccionRoutes);
router.use('/plantas', plantaRoutes);
router.use('/roles-usuario', rolUsuarioRoutes);
router.use('/estados-pedidos', estadoPedidoRoutes);
router.use('/graficos', graficosRoutes);
router.use('/informes-semanales', informeSemanal);
router.use('/dux', duxRoutes); 
//router.use('/chat', chatRoutes); 
router.use('/conversaciones-bot', conversacionBotRoutes);
router.use('/facturas', facturaRoutes);
router.use("/eficiencia", eficienciaRoutes);
router.use("/personalDux", personalDuxRoutes);
router.use("/materias-primas", MateriaPrimaRoutes);
router.use("/composiciones", composicionRoutes);
router.use("/ordenes-trabajo", ordenTrabajoRoutes);
router.use('/proveedores', proveedorRoutes);
router.use('/configuraciones', ConfiguracionSistema);

export default router;
