export const ESTADOS_PEDIDO = {
  PENDIENTE: 1,
  CONFIRMADO: 2,
  PREPARANDO: 3,
  TERMINADO: 4,
  ENVIADO: 5,
  FINALIZADO: 6,
  RECHAZADO: 7,
  CANCELADO: 8,
}

export const ESTADOS_DUX = {
  PENDIENTE: 1,
  FACTURADO_PARCIAL: 2,
  FACTURADO: 3,
  CERRADO: 4, 
};
